# Data Science Tools and Ecosystem

## Author
Juan Felipe Pinto

In this notebook, Data Science Tools and Ecosystem are summarized.

**Objectives:**
- List popular languages for Data Science
- Commonly uesd libraries used by Data Scientist
- Data Science Tools

Some of the popular languages that Data Scientists use are:
1. R
2. Python
3. SQL

Some of the commonly used libraries used by Data Scientists include:
1. Matplotlib
2. NumPy
3. Pandas
4. Scikit

| Data Science Tools |
| ------------------ |
| Visual Studio Code |
| JupyterLab |
| R Studio |

### Below are a few examples of evaluating arithmetic expressions in Python

In [2]:
#This a simple arithmetic expression to mutiply then add integers
(3*4)+5

17

In [3]:
#This will convert 200 minutes to hours by diving by 60
200/60

3.3333333333333335